# apiVersion: v1
# kind: Service
# metadata:
#   name: rabbitmq
#   namespace: gamestore
# spec:
#   selector:
#     app: rabbitmq
#   type: NodePort # Alterado para permitir acesso externo
#   ports:
#     - name: amqp
#       port: 5672
#       targetPort: 5672
#       nodePort: 30672 # Porta externa para envio/recebimento de mensagens
#     - name: management
#       port: 15672
#       targetPort: 15672
#       nodePort: 31672 # Porta externa para acessar o Painel Web (Interface)