# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rabbitmq
#   namespace: gamestore
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rabbitmq
#   template:
#     metadata:
#       labels:
#         app: rabbitmq
#     spec:
#       containers:
#         - name: rabbitmq
#           image: rabbitmq:3-management
#           ports:
#             - containerPort: 5672
#             - containerPort: 15672
#           env:
#             - name: RABBITMQ_DEFAULT_USER
#               value: guest
#             - name: RABBITMQ_DEFAULT_PASS
#               value: guest
#           volumeMounts:
#             - mountPath: /var/lib/rabbitmq
#               name: rabbitmq-storage
#       volumes:
#         - name: rabbitmq-storage
#           persistentVolumeClaim:
#             claimName: rabbitmq-pvc