apiVersion: v1
kind: Secret
metadata:
  name: usersapi-secrets
  namespace: gamestore
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=users_db;Username=postgres;Password=postgres"
  Jwt__Key: "super-secret-key-change-this-32bytes-min"
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"