apiVersion: v1
kind: Service
metadata:
  name: usersapi-service
  namespace: gamestore
spec:
  type: NodePort
  selector:
    app: usersapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080 